### ISSUE TITLE
I wish to have the relevant hyper-parameters and commands for SOTA results on Cora.

### ISSUE THREAD

**Issue by xinghun0525** [ConferencesCode/SimGNN#3]
It is fascinating to integrate SimRank and GNN (Graph Neural Networks) in an organic manner and showcase excellent results! I am particularly interested in the optimal results achieved on the Cora dataset in your project. I would greatly appreciate it if you could provide the relevant hyperparameters and commands for reproducing the SOTA results on Cora.

**Comment by ConferencesCode** [comment]
Thanks for your attention really! This repo currently provides the essential code for reproducing results for the six large-scale datasets. The complete version will be updated after the decision of the paper submitted. (It seems it's not proper to update the repo during the reviewing period) For your interest, pls leave me an email if possible and i'll send you relevant information.

**Comment by xinghun0525** [comment]
geqian@pku.edu.cn 
This is my email address (I have just sent you an email request), thank you very much! I sincerely appreciate it and wish the acceptance of the paper!

**Comment by ConferencesCode** [comment]
You're welcome~
